### ISSUE TITLE
sitemesh3+freemarker refresh Cache still

### ISSUE THREAD

**Issue by lihua123569** [sitemesh/sitemesh3#100]
When I change the content of the HTML page, the front refresh content will not change, only after the mandatory refresh to change. Why, how to deal with it?

**Comment by codeconsole** [comment]
This does not sound like a sitemesh issue.  Can you be more specific?  Are you making changes during development or are you referring to dynamic changes in a production environment?   

If this is still an issue, please re-open after providing an example.   Feel free to use the freemarker example app:
https://github.com/sitemesh/sitemesh3/tree/master/sitemesh-examples-springboot
