### ISSUE TITLE
Major bug

### ISSUE THREAD

**Issue by 120011676** [sitemesh/sitemesh3#101]
![1](https://cloud.githubusercontent.com/assets/1992933/18260258/99ec31e6-741e-11e6-9b57-bde97e6f0e14.png)
![2](https://cloud.githubusercontent.com/assets/1992933/18260261/9a13d3d6-741e-11e6-84a7-1d50d4c5b794.png)
![3](https://cloud.githubusercontent.com/assets/1992933/18260259/9a139eca-741e-11e6-9bdd-84388f2499df.png)
![4](https://cloud.githubusercontent.com/assets/1992933/18260260/9a13ee5c-741e-11e6-8c1d-85d775e985d7.png)

version:3.0.1   3.0.0

**Comment by 120011676** [comment]
The problem in tomcat9 (M9) tomcat8 (8.5.4), tomcat7 (7.0.70) no problem.

**Comment by codeconsole** [comment]
Verified working on 10.1.10.  Please re-open if this is still an issue.
