### ISSUE TITLE
could exclue ajax/json/responseBody?

### ISSUE THREAD

**Issue by githubyong** [sitemesh/sitemesh3#102]
could it exclude ajax or json or mvc responsebody,now i have to add all ajax path to the exclude mapping list,it is really annoying.

**Comment by codeconsole** [comment]
Ajax requests should not be requesting `text/html`   
Are your ajax request requesting `text/html`?

**Comment by codeconsole** [comment]
if this is still an issue, please address it here:
https://github.com/sitemesh/sitemesh3/issues/102
