### ISSUE TITLE
doesn't support post

### ISSUE THREAD

**Issue by githubyong** [sitemesh/sitemesh3#103]
I had import sitemesh3 into my project,but it does't support post method.My env is spring4.x,tomcat8 and jdk8.
some errors like this " java.io.IOException: Could not dispatch to decorator
    at org.sitemesh.webapp.WebAppContext.decorate(WebAppContext.java:150)"

**Comment by flopma** [comment]
Make sure your target is accepting POST. I guess you are trying to access a Spring MVC resource which does not accept POST.
