### ISSUE TITLE
HELP in Sitemesh 3 with Parameter

### ISSUE THREAD

**Issue by jclayer** [sitemesh/sitemesh3#107]
Hi,

I need help with working on sitemesh 3 and url parameters, I have been trying to find how it works but to no valid.

Let's say I have a mapping path with **abc.action?print=true** then I want it to be map to decorator **printpage.jsp** and if it's just **abc.action** then it will be map to decorator **defaultpage.jsp**.

Thank you in advance.

**Comment by codeconsole** [comment]
Duplicate https://github.com/sitemesh/sitemesh3/issues/90
