### ISSUE TITLE
I can't customize the profile path.(sitemesh3.xml under idea).

### ISSUE THREAD

**Issue by lapDog** [sitemesh/sitemesh3#108]
![image](https://cloud.githubusercontent.com/assets/11813246/22145808/c58765ca-df3d-11e6-8bbd-3c84e8d7019d.png)
![image](https://cloud.githubusercontent.com/assets/11813246/22145836/d57cc43e-df3d-11e6-9e79-5d381fdcfe57.png)
change  <param-value>sitemesh3.xml</param-value>,dosen't work. Can only be placed under the default path.
![image](https://cloud.githubusercontent.com/assets/11813246/22146180/b66c2af2-df3e-11e6-81b8-eabf33c59257.png)
Error loading using absolute path,need help!

**Comment by lapDog** [comment]
Temporarily change the absolute path to <param-value>WEB-INF/classes/sitemesh3.xml</param-value>

**Comment by codeconsole** [comment]
It sounds like you resolved your issue?  If not, please re-open.
