### ISSUE TITLE
Url case sensitive

### ISSUE THREAD

**Issue by fantasylion** [sitemesh/sitemesh3#109]
```
 <decorator name="home-page" page="layout/home_main.jsp">
		<pattern>/register.htm</pattern>
 </decorator>
```
It doesn't work if I request /REGISTER.HTM . What do I need to do to make it work? Some one can tell me?please

**Comment by aadrian** [comment]
> It doesn't work if I request /REGISTER.HTM 

Why should it? URLs **are** case sensitive https://www.w3.org/TR/WD-html40-970708/htmlweb.html

> What do I need to do to make it work? 

Request ```/register.htm``` and rename the files accordingly, since filenames on Unix platforms are also case sensitive, so two files: ```register.htm``` and ```REGISTER.HTM``` can exist both in the same directory.

**Comment by FantasyLions** [comment]
Yeah! You are right. Is so embarrassed, my boss want me to do this.

**Comment by codeconsole** [comment]
Works as intended.
