### ISSUE TITLE
Multi decorators could not matching

### ISSUE THREAD

**Issue by yee333** [sitemesh/sitemesh3#111]
If i config sitemesh.xml 

	<mapping>
		<path>/demo/audit/*</path>
		<decorator>/WEB-INF/decorators/edit.jsp</decorator>
		<decorator>/WEB-INF/decorators/public.jsp</decorator>
	</mapping>

	<mapping>
		<path>/demo/edit/*</path>
		<decorator>/WEB-INF/decorators/edit.jsp</decorator>
		<decorator>/WEB-INF/decorators/public.jsp</decorator>
	</mapping>

i could not render from audit.jsp. it seems that just match the last mapping
so... I put path to property

	<mapping path="/demo/audit/*">
		<decorator>/WEB-INF/decorators/edit.jsp</decorator>
		<decorator>/WEB-INF/decorators/public.jsp</decorator>
	</mapping>

	<mapping path="/demo/edit/*">
		<decorator>/WEB-INF/decorators/edit.jsp</decorator>
		<decorator>/WEB-INF/decorators/public.jsp</decorator>
	</mapping>
success!!!

**Comment by dasm83** [comment]
Could you specify library's version u're using ? I tried this, but now my pages aren't decorated at all

**Comment by codeconsole** [comment]
Just out of curiosity, have you tried:

```xml
<mapping>
	<path>/demo/audit/*</path>
	<decorator>/WEB-INF/decorators/edit.jsp,/WEB-INF/decorators/public.jsp</decorator>
</mapping>
```

**Comment by codeconsole** [comment]
Please note in the next release `/WEB-INF/decorators/` will be the default prefix so that the configuration can be simplified to:

```xml
<sitemesh>
  <mapping path="/demo/audit/*" decorator="edit.jsp,public.jsp" />
  <mapping path="/demo/edit/*" decorator="edit.jsp,public.jsp" />
</sitemesh>
```
