### ISSUE TITLE
Decoration is based on setting the content type or not

### ISSUE THREAD

**Issue by flopma** [sitemesh/sitemesh3#112]
`org.sitemesh.webapp.contentfilter.HttpServletResponseBuffer.enableBuffering(String)` is enabling the decoration process. However, this is called by method `org.sitemesh.webapp.contentfilter.HttpServletResponseBuffer.setContentType(String)`.

If this last method is not called, Sitemesh will not decorate. Actually, this is creating an issue in the following case:
- we use Spring MVC
- Freemarker views

If Freemarker is throwing exception because of a broken template, the application server will catch the exception and handles it by processing the request with an ERROR dispatcher.

First issue is that Sitemesh will not process the error page handling because it thinks the request has already been processed by Sitemesh, see https://github.com/sitemesh/sitemesh3/issues/25#issuecomment-296993960

2nd issue is that Spring MVC views call .setContentType() only if the response has not content type set. In the case of this case, during processing of the error page, Spring MVC sees the response content type is already set and will not call method .setContentType(). Sitemesh will not enable buffering and will not decorate the error page.

Can you fix this please? The buffering enabling algorithm should perhaps not be based and the calling of method .setContentType() only.

Our current workaround is to add a filter after Sitemesh and call .setContentType() when the error page is being processed.

**Comment by codeconsole** [comment]
Is this still an issue?  If so, we are willing to fix it right away. We have a working Freemarker example in the Spring Boot example application.

**Comment by flopma** [comment]
Hello @codeconsole AFAIK, yes it is still biting us...

**Comment by codeconsole** [comment]
ok, thanks for the update. We can plan on getting it fixed between M2 and the final release. 

Can you please give some info on your environment?
Are you using Spring Boot?
What Java version / Servlet API version?
What Application Server?

**Comment by flopma** [comment]
Ok,

For this webapp, I don't use Spring Boot, but I do use Spring MVC, Spring Security, Spring Data. Sitemesh v3.0.1
JVM is v11
Servlet API v4.0
And app server is Tomcat 9.0.73.

Thx!

**Comment by codeconsole** [comment]
Hi @flopma,

Are you able to modify the sample app to replicate the problem?

```
git clone https://github.com/sitemesh/sitemesh3
cd sitemesh3
git checkout 3.1.x
cd sitemesh-examples-hellowebapp
```

Running either command will start sitemesh-examples-hellowebapp
```
./gradlew tomcatRun
./gradlew bootRunRun
```

**Comment by codeconsole** [comment]
@flopma, perhaps this is already working with M2? Or if you could please modify the sample app so we can get this fixed and issue the final release

**Comment by flopma** [comment]
Hello ! Will try my best to get this tested next week and provide feedback. Thx for your follow-up on this !
 
	  Original Message

**Comment by codeconsole** [comment]
Thanks, feel free to ask any questions on configuring anything.

**Comment by flopma** [comment]
Hello @codeconsole I was trying to see if the problem was still there in our app with sitemesh v 3.2.0-M2 but it seems that version has been compile with JDK 1.7 while https://sitemesh.github.io/sitemesh-website/getting-started.html says minimum JDK should be 1.5. Am I wrong somewhere? Thx

**Comment by codeconsole** [comment]
HI @flopma, you have to use 3.1.0-M2

```
git clone https://github.com/sitemesh/sitemesh3
cd sitemesh3
git checkout 3.1.x
cd sitemesh-examples-hellowebapp
gradle tomcatRun
```

**Comment by flopma** [comment]
Ok thx @codeconsole 

I have tested against 3.1.0-M2.
Here are my findings:

- I needed to call setDecoratorPrefix() when building SiteMeshFilterBuilder
- setIncludeErrorPages() true or false does not change/help anything
- in the web.xml, I have to add the <dispatcher>ERROR</dispatcher> present

then error page is correctly decorated by SiteMesh.

What do you think?

**Comment by codeconsole** [comment]
Hi @flopma,

yeah, setDecoratorPrefix is now required if you don't want your decorators in the `WEB-INF/decorators` folder.

`setIncludeErrorPages()` is somewhat irrelevant at this time, but may change in the future.  It should always default to true.

yes, `ERROR` needs to be present however you no longer need a web.xml if you use all default behavior. 

Regarding:
> 2nd issue is that Spring MVC views call .setContentType() only if the response has not content type set. In the case of this case, during processing of the error page, Spring MVC sees the response content type is already set and will not call method .setContentType(). Sitemesh will not enable buffering and will not decorate the error page.

Are you still experiencing the `setContentType()` issue or is everything now resolved for you?

**Comment by flopma** [comment]
Yes, looks like your commit in https://github.com/sitemesh/sitemesh3/commit/be4c60809aa5d56d8443e3d3a334913ffd0cd380 fixed it.

It's working fine for me now!
Thx for the fix :-)

**Comment by codeconsole** [comment]
great, thanks for verifying
