### ISSUE TITLE
Can't generate the Lexer.java  when I flow the TagTokenizer.java's comment

### ISSUE THREAD

**Issue by LeYu** [sitemesh/sitemesh3#115]
I flow the common ,use mvn jflex:generate under the folder sitmesh, maven tell me it's success, but where is 
my Lexer.java

**Comment by fightingaman** [comment]
you can found it

**Comment by codeconsole** [comment]
1. Use Gradle instead.
2. Don't execute a clean and jar command simultaneously (e.g. `./gradlew clean jar` will not work).  If you need to run clean, do it separately
```
./gradlew clean
./gradlew jar
```
