### ISSUE TITLE
JSP error page is not decorated

### ISSUE THREAD

**Issue by pioterj** [sitemesh/sitemesh3#116]
Default JSP error page is not decorated by SiteMesh 3 in Spring Boot app despite `includeErrorPages` being set to `true`.

# Steps to reproduce
- Unpack attached sample project
- Run `./gradlew bootRun`
- Open `http://localhost:8080/non-existent` and `http://localhost:8080/foo`
- Unlike `http://localhost:8080/` the pages are not decorated as`Decorated by Sitemesh` string is not displayed

# Sample project
Full project: [sitemesh-issue.zip](https://github.com/sitemesh/sitemesh3/files/1308286/sitemesh-issue.zip)

Spring configuration class (also provided in the attached sample project):
```java
@Configuration
public class WebConfiguration extends WebMvcConfigurerAdapter {

    @Bean
    public InternalResourceViewResolver setupViewResolver() {
        InternalResourceViewResolver resolver = new InternalResourceViewResolver();
        resolver.setPrefix("/WEB-INF/jsp/");
        resolver.setSuffix(".jsp");
        resolver.setViewClass(JstlView.class);
        return resolver;
    }

    @Bean
    public FilterRegistrationBean siteMeshFilter() {
        FilterRegistrationBean filter = new FilterRegistrationBean();
        Filter siteMeshFilter = new SiteMeshFilterBuilder()
            .addDecoratorPath("/*", "/WEB-INF/jsp/decorator.jsp")
            .setIncludeErrorPages(true)
            .create();
        filter.setFilter(siteMeshFilter);
        filter.setUrlPatterns(Arrays.asList("/*"));
        // filter.setDispatcherTypes(ERROR); // with this error page is decorated but not other pages
        // filter.setDispatcherTypes(REQUEST, FORWARD, ERROR); // this doesn't work either
        return filter;
    }
}
```

**Comment by pioterj** [comment]
I just found this comment: https://github.com/sitemesh/sitemesh3/issues/25#issuecomment-991330. It works after adding `filter.setDispatcherTypes(ERROR, FORWARD);`

**Comment by codeconsole** [comment]
Works as intended.
