### ISSUE TITLE
Even index.html in the example hellowebapp cannot be load completely in Chrome

### ISSUE THREAD

**Issue by luchenguang** [sitemesh/sitemesh3#119]
I'm using Tomcat 9, Java 1.8, IDEA 2017.3.5, Sitemesh 3.0.1 and I want to decorate index.html in sitemesh-examples-hellowebapp but it failed to be load completely. Just like follows.
<img width="715" alt="qq20180607-123734 2x" src="https://user-images.githubusercontent.com/36319763/41078493-bdf1ef08-6a4f-11e8-961f-ea9c1f16c1ec.png">
<img width="496" alt="qq20180607-123823 2x" src="https://user-images.githubusercontent.com/36319763/41078496-c3a182ba-6a4f-11e8-983f-fc29143fafa0.png">
There is nothing behind the "applied to". Why? I didn't change anything in this project.

**Comment by wang-hu** [comment]
check the mapping path. It‘s a papping request path not a jsp page path.

**Comment by codeconsole** [comment]
Latest example apps verified working.  If you still have a problem, re-open.
