### ISSUE TITLE
Servlet container test suite

### ISSUE THREAD

**Issue by sitemesh** [sitemesh/sitemesh3#12]
Implement container test suite.

http://wiki.github.com/sitemesh/sitemesh3/design-doc-container-test-suite

**Comment by codeconsole** [comment]
https://github.com/sitemesh/sitemesh3/wiki/Design-Doc%3A-Container-Test-Suite

**Comment by codeconsole** [comment]
Stale issue. Not a high priority. I personally don’t have the time. Re-open if you have a pull request for me ;)
