### ISSUE TITLE
Inconsistent case sensitivity in path matching

### ISSUE THREAD

**Issue by yehara** [sitemesh/sitemesh3#121]
When a path pattern contains the wildcard(*), a case-insensitive match is performed. But when a path pattern does not contain the wildcard, a case-sensitive match is performed. How can I do case-sensitive matching using the wildcard?

version: 3.0.1

### Example
```
<sitemesh>
  <mapping path="/Foo/Bar" decorator="/foobar-decorator" />
  <mapping path="/Baz/*" decorator="/baz-decorator" />
  <mapping path="/*" decorator="/default-decorator" />
</sitemesh>
```

- `/foo/bar` -> default-decorator  ( the pattern `/Foo/Bar` doesn't match `/foo/bar` )
- `/baz/xxx` -> baz-decorator  ( the pattern `/Baz/*` matches `/baz/xxx` )

**Comment by codeconsole** [comment]
https://github.com/sitemesh/sitemesh3/blob/f738762951d9bfabcdf8f247ceac97fbfdf88a89/sitemesh/src/main/java/org/sitemesh/config/PathMapper.java#L87-L92
