### ISSUE TITLE
how to custom same Tag in jsp's page

### ISSUE THREAD

**Issue by weiwangda2014** [sitemesh/sitemesh3#125]
i have defined in decorator
<sitemesh:write property="JavaScripts"/>

and i have defined a  page ,as follows

```
<JavaScripts>
    a......
</JavaScripts>

<JavaScripts>
    b......
</JavaScripts>
```

the result is 

`a....`

but now, i need result is

`    a......    and     b......`

Is there any way to fix my problem？

**Comment by codeconsole** [comment]
Example:
https://github.com/sitemesh/sitemesh3/issues/99
