### ISSUE TITLE
Pass data into decorator jsp from content JSP

### ISSUE THREAD

**Issue by sarathAchu** [sitemesh/sitemesh3#128]
need to pass some values from content jsp to decorator jsp page

This can be achieved on sitemesh version 2 through

`<decorator:usePage id="samplepageobj" /> and getProperty`

For example

I am using, login.jsp as content page and main.jsp as it's decorator page

On login page, I have specified the content on html tag
`<meta name="param1" content="Parameter1">`

On main.jsp page am loading this value

```
<decorator:usePage id="pageobj" />
<% String value1 = pageobj.getProperty("meta.param1"); %>
``` 

how it can be achieved through sitemesh 3 ?

**Comment by codeconsole** [comment]
Example:
https://github.com/sitemesh/sitemesh3/issues/99
