### ISSUE TITLE
Example for Offline Site Generation ?

### ISSUE THREAD

**Issue by aadrian** [sitemesh/sitemesh3#130]
Hi,

Is there any example on how to use the "Offline Site Generation" feature?

Thank you.

**Comment by codeconsole** [comment]
https://github.com/sitemesh/sitemesh-website/

**Comment by codeconsole** [comment]
Here is a link how to do it in java:

https://sitemesh.github.io/sitemesh3/javadoc/3.1.x/org/sitemesh/offline/SiteMeshOffline.html
