### ISSUE TITLE
Page for projects using SiteMesh !

### ISSUE THREAD

**Issue by aadrian** [sitemesh/sitemesh3#133]
Hi,

Please add a page for projects/frameworks using SiteMesh and a way(/notes) to easily collect this information from the users (Discussion/Form/Ticket etc).

Just the simple number of "stars" on GitHub by no means reflect the usage and usefulness of this project !

Thank you.

**Comment by codeconsole** [comment]
I just enabled discussions.  If you are looking for something more specific, please let me know and provide an example of what you would like it to look like.
