### ISSUE TITLE
How to use the multiple page jsp in one jsp when using the sitemesh 3?

### ISSUE THREAD

**Issue by NguyenK3** [sitemesh/sitemesh3#136]
> I want to use above the left__container is body 1 and main__container is body 2.
```
<!--Content-->
<div class="content__container">
    <div class="left__container">
        <sitemesh:write property="body"></sitemesh:write>
    </div>
    <div class="main__container">
        <sitemesh:write property="body"></sitemesh:write>
    </div>
</div>
```

**Comment by codeconsole** [comment]
You want to write the contents of the <body></body> tag twice on one page?

**Comment by NguyenK3** [comment]
> You want to write the contents of the <body></body> tag twice on one page?

> I mean this These 2 jsp pages are on the same page representing 2 different bodies.
```
<!--Content-->
<div class="content__container">
    <div class="left__container">
        <%@ include file="left.jsp"/>
    </div>
    <div class="main__container">
          <%@ include file="main.jsp"/>
    </div>
</div>
```

**Comment by codeconsole** [comment]
> > You want to write the contents of the  tag twice on one page?
> 
> > I mean this These 2 jsp pages are on the same page representing 2 different bodies.
> 
> ```
> 
> <div class="content__container">
>     <div class="left__container">
>         <%@ include file="left.jsp"/>
>     </div>
>     <div class="main__container">
>           <%@ include file="main.jsp"/>
>     </div>
> </div>
> ```

I still do not understand what you are trying to do?  Is that the page you are decorating or is that the decorator?
Please provide a more complete example including the page you want decorated and the decorator you want to decorate the page.

**Comment by NguyenK3** [comment]
> > > You want to write the contents of the  tag twice on one page?
> > 
> > > I mean this These 2 jsp pages are on the same page representing 2 different bodies.
> > 
> > ```
> > 
> > <div class="content__container">
> >     <div class="left__container">
> >         <%@ include file="left.jsp"/>
> >     </div>
> >     <div class="main__container">
> >           <%@ include file="main.jsp"/>
> >     </div>
> > </div>
> > ```
> 
> I still do not understand what you are trying to do?  Is that the page you are decorating or is that the decorator?
> Please provide a more complete example including the page you want decorated and the decorator you want to decorate the page.

> - It is my folder
> webapp
│
> ├── view
│   ├── home
│   │   ├── homepage.jsp
│   │
│   ├── component
│       ├── left.jsp
│       ├── home.jsp
│
└── WEB-INF
    ├── decorators
        ├── decorator.html
> In the homepage will use two jsp which are left.jsp and home.jsp
> How should I write a decorator page to use the same 2 jsp pages in the homepage?

**Comment by codeconsole** [comment]
The decorator would be applied to homepage.jsp, not to the includes.

```html
<head>
  <meta name="decorator" content="decorator.html" />
</head>
```

You just add that to the homepage to apply it.  If you want to select parts of the page in the decorator, you can use a DivExtractingRule or a ContentBlockExtractingRule.

I still don't really understand what you are asking.  Perhaps it is best if you provide a minimal complete working app and create the files how you want them to work.

You can start by modifying https://github.com/sitemesh/sitemesh3/tree/master/sitemesh-examples-hellowebapp

**Comment by codeconsole** [comment]
Is this what you want? https://github.com/codeconsole/spring6-filter/commit/9ac507fe0298aef8c8f11c9cb07f1e573d48d932

**Comment by codeconsole** [comment]
Here is a decorator applied to a page with 2 includes.

https://github.com/codeconsole/spring6-filter

Are you wanting to ignore the body in the decorator and only select the content from the divs?  If so, you just use a `DivExtractingRule`, but I still have no idea what you want

**Comment by NguyenK3** [comment]
> Here is a decorator applied to a page with 2 includes.
> 
> https://github.com/codeconsole/spring6-filter
> 
> Are you wanting to ignore the body in the decorator and only select the content from the divs?  If so, you just use a `DivExtractingRule`, but I still have no idea what you want

> Yes, that's it. But I want to use it on the webapp that not - use on sping6-filter

**Comment by codeconsole** [comment]
ok, well, here you go:

Use the [nospring](https://github.com/codeconsole/spring6-filter/tree/nospring) branch then.
