### ISSUE TITLE
sitemesh:write default property value

### ISSUE THREAD

**Issue by morrica** [sitemesh/sitemesh3#137]
Older versions of sitemesh supported the ability to provide a "default" for a property if it was not found in the page being decorated. Is this functionality available in sitemesh 3?

Something like 
`<sitemesh:write property="meta.description" default="My default description"/>` 
or
`<sitemesh:write property="meta.description">My default description</sitemesh:write>`

Seem like they would make sense but neither work. I am unable to locate the `<sitemesh:write>` code in the source to examine any additional parameters that might be available for setting the default.

If this functionality currently exists please let me know. If not, I think it would be a very useful feature to add.

**Comment by codeconsole** [comment]
Hi @morrica,

It looks like this was intended, but never implemented.

The source for `sitemesh:write` is [here](https://github.com/sitemesh/sitemesh3/blob/master/sitemesh/src/main/java/org/sitemesh/content/tagrules/decorate/SiteMeshDecorateRule.java)

I will look into getting this implemented.

**Comment by codeconsole** [comment]
The correct syntax is `<sitemesh:write property="meta.description">My default description</sitemesh:write>`  I'll try to put together a demo in the next few days.

**Comment by codeconsole** [comment]
@morrica might be a bug, let me look into it

**Comment by codeconsole** [comment]
@morrica so it looks like for SiteMesh 3 it was never designed to work that way.  It only showed the default content if blank content was being decorated.  I am not quite sure the scenario where one would decorate null content, but that was the design.

I just updated `sitemesh:write` to now also display the default content if the property is not found so `<sitemesh:write property="meta.description">My default description</sitemesh:write>` should now work and display `My default description` if that description meta tag is not on the page. 

You can test it out by using the latest SNAPSHOT build.

```
<dependency>                                             
  <groupId>org.sitemesh</groupId>                      
  <artifactId>spring-boot-starter-sitemesh</artifactId>
  <version>3.2.0-SNAPSHOT</version>                                
</dependency>                                            
<dependency>                                             
  <groupId>org.sitemesh</groupId>                      
  <artifactId>sitemesh</artifactId>                    
  <version>3.2.0-SNAPSHOT</version>                          
</dependency> 
```

You can resolve it using the SNAPSHOT repository: `https://oss.sonatype.org/content/repositories/snapshots/`

**Comment by morrica** [comment]
@codeconsole Thank you very much!
