### ISSUE TITLE
Spring Boot Autoconfigure bad defaults

### ISSUE THREAD

**Issue by superdrenner** [sitemesh/sitemesh3#139]
When using spring-boot-starter-sitemesh the property `sitemesh.decorator.attribute` is defaulted to an empty string which causes the builder to always register a RequestAttributeDecoratorSelector instead of the default MetaTagBasedDecoratorSelector.

```java
    // org/sitemesh/autoconfigure/SiteMeshAutoConfiguration.java
    // I think this should really be: ${sitemesh.decorator.attribute}
    @Value("${sitemesh.decorator.attribute:}")
    private String attribute;
```

I was able to work around this issue with the following:

```kotlin
    @Bean("siteMeshFilter")
    fun configurableSiteMeshFilter() = ConfigurableSiteMeshFilter()
```

**Comment by codeconsole** [comment]
Thanks for the report.  `RequestAttributeDecoratorSelector` extends `MetaTagBasedDecoratorSelector`, but obviously the behavior you are describing is not desired.

**Comment by superdrenner** [comment]
@codeconsole for some reason the mappings from the xml configuration were being lost when the autoconfig ran. Maybe xml configuration is not compatible with the spring boot autoconig?

**Comment by codeconsole** [comment]
@superdrenner you want to give the latest snapshot a try?

```gradle
repositories {
    mavenCentral() 
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}
```
```gradle
dependencies {
    runtimeOnly 'org.sitemesh:sitemesh:3.2.1-SNAPSHOT'
}
```

**Comment by codeconsole** [comment]
> @codeconsole for some reason the mappings from the xml configuration were being lost when the autoconfig ran. Maybe xml configuration is not compatible with the spring boot autoconig?

@superdrenner if you are using spring boot, sitemesh3.xml should not be used.  Mappings should be configured via the [yaml file](https://github.com/sitemesh/sitemesh3/blob/master/examples/springboot/src/main/resources/config/application.yml):
```yaml
sitemesh:
  decorator:
    exclusions: /assets/*
    mappings:
      - path: /*
        decorator: default.html
```
