### ISSUE TITLE
Move SiteMesh website out of sitemesh3 repo

### ISSUE THREAD

**Issue by sitemesh** [sitemesh/sitemesh3#15]
www.sitemesh.org should vary independently from sitemesh3 and sitemesh2, and the additional weight shouldn't reside in the main code base.

Migrate from: http://github.com/sitemesh/sitemesh3/tree/master/sitemesh-docs
To: http://github.com/sitemesh/sitemesh-website/tree/master/

**Comment by codeconsole** [comment]
completed
