### ISSUE TITLE
don't wait while decorated body is completely generated

### ISSUE THREAD

**Issue by ekuleshov** [sitemesh/sitemesh3#38]
When decorating a large page body SM3 wait when decorated page body is completely produced, i.e. <sitemesh:write property='body'> tag don't write out decorated body until decorated page is returned completely.

To improve performance in such case it could start streaming chunks of the decorated page before it is completely generated.

**Comment by hansgru** [comment]
+1
IMO this functionality is critical for real usage scenarios.

**Comment by codeconsole** [comment]
Feel free to submit a pull request
