### ISSUE TITLE
Asynchronous Servlet Not Supported

### ISSUE THREAD

**Issue by peterwkc** [sitemesh/sitemesh3#43]
Hello, I'm implemented  asynchronous servlet using spring which return Callable<String> but the view is not decorated by sitemesh.

Does sitemesh 3  support decorate the view with asynchronous servlet ?

Thanks.

**Comment by codeconsole** [comment]
https://github.com/sitemesh/sitemesh3/commit/522250ba72bfebb11a81ddeead2145710282b284
