### ISSUE TITLE
Not working at the Wildfly AS

### ISSUE THREAD

**Issue by dtelaroli** [sitemesh/sitemesh3#59]
My app working fine in JBoss 7.1.1, but if I update to Wildfly the jsps not be decorated.
The Wildfly will be supported by Sitemesh?

**Comment by BenjaminViet** [comment]
Hi all, anyone has worked arround on this? I am in the same issue and still not know th correct approach.
Any help will be appriciated. Thanks.

**Comment by dtelaroli** [comment]
@BenjaminViet I migrated to Tomcat 8

**Comment by BenjaminViet** [comment]
Hi dtelaroli,

Thanks for your quick answer. But I do not have any idea to use other right now because my project includes EJBs, So there is any way to go with it or an alternative? Thanks.

**Comment by dtelaroli** [comment]
You will need choose between keep the legacy jboss or migrate your layout engine... This project it seems abandoned.
