### ISSUE TITLE
“Not Modified” header followed by unexpected content body

### ISSUE THREAD

**Issue by xtianus** [sitemesh/sitemesh3#62]
When using sitemesh 3.0.0 with struts2 behind an apache http server, whenever I fetch content from the /struts context and get a 304 "Not Modified", I also receive the file body in the response. This corrupts any file request after that one, resulting in an unstable web site.
Please see this post on StackOverflow for the details: http://stackoverflow.com/questions/24430135/not-modified-header-followed-by-unexpected-content-body

I have done some investigations in the sources and found out that, although sitemesh might not be held responsible for this behavior, still it handles "not modified" files its own way, by forcing struts into writing them to the response body.

Please do not underestimate this problem. It really makes web sites unusable, especially when coupled with some plugin that pulls big files from the /struts context, like the struts2-jquery plugin. In my case, it corrupts my own javascript and the site doesn't respond anymore to user clicks.

**Comment by wondee** [comment]
Any update on this issue?

**Comment by codeconsole** [comment]
The only issue I experienced with Not Modified was when there was a conflicting servlet-api jar was added to the war.  Removing the jar and using the container provided servlet-api resolved this issue. 

If this is still an issue, please provide a minimal example war and we will fix it for you.

Specifically, use https://github.com/sitemesh/sitemesh3/tree/master/sitemesh-examples-hellowebapp and make the minimal changes necessary to replicate the issue.

**Comment by codeconsole** [comment]
Can't replicate.
