### ISSUE TITLE
Blank response for static HTMLs served by Spring MVC

### ISSUE THREAD

**Issue by sunildmonte** [sitemesh/sitemesh3#64]
I'm using Spring MVC, and my static error pages (e.g. 404 error page) are located in a "resources" directory:
```
  /resources/error-404.html
  /resources/error-403.html
  etc.
```
Spring lets you define "handlers" for static resources such as this. When a requested URL is not found, in order to return the defined "error-404.html" to the browser, Spring uses a handler class. The handler in question is [ResourceHttpRequestHandler](http://grepcode.com/file/repo1.maven.org/maven2/org.springframework/spring-webmvc/4.0.4.RELEASE/org/springframework/web/servlet/resource/ResourceHttpRequestHandler.java#ResourceHttpRequestHandler). 

What's happening is: a blank response is returned to the browser (though the error code is 404 as expected). When i debug SiteMesh's `ContentBufferingFilter` and `HttpServletResponseBuffer`, I can see the HTML in the buffer. But it doesn't get back to the browser. 

Note: I'm excluding "/resources/*" in my config I.e.
```java
    @Override
    protected void applyCustomConfiguration(SiteMeshFilterBuilder builder) {
        builder
        ...
        .addExcludedPath("/resources/*") // ignore static resources
        ;
    }
```
But I don't think that's relevant to this issue, since the original requested URL is very much an included URL.

**Comment by codeconsole** [comment]
Closing due to no response given.
