### ISSUE TITLE
Static files can't be decorated under Spring MVC/Tomcat

### ISSUE THREAD

**Issue by madth3** [sitemesh/sitemesh3#65]
The result of applying a decorator to a simple HTML file is a truncated file. If the file is changed to a JSP the decoration process works correctly. 

I'm mentioning the server since there was a similar bug in Sitemesh 2 with Tomcat but the complete details (and perhaps even a fix) were in the OpenSymphony bug tracker. maye Spring is not really part of the issue.

Java 1.8
Spring 4.0.5.Release
Tomcat 8.0.3

**Comment by viruscamp** [comment]
Commit 35896ae has nothing to do with this issue .
This issue is unresolved , and is duplicated with #68 .
