### ISSUE TITLE
Embedded configuration in Spring XML

### ISSUE THREAD

**Issue by sitemesh** [sitemesh/sitemesh3#7]
Allow SiteMesh to be configured directly in a Spring XML config file, so as not to force Spring users to add yet another config file.

See design doc for example: http://wiki.github.com/sitemesh/sitemesh3/design-doc-configuration

Implementation notes:
- Ensure that we do not introduce any mandatory Spring dependencies for users who don't use Spring.
- Details about extending the Spring XML can be found here: http://static.springframework.org/spring/docs/2.5.x/reference/extensible-xml.html 
- It should be possible to reuse the code the existing XML config code as it reads directly from an Element, which is what's required to plug into Spring: http://github.com/sitemesh/sitemesh3/tree/master/sitemesh/src/main/java/org/sitemesh/config/xml

**Comment by codeconsole** [comment]
https://github.com/sitemesh/sitemesh3/wiki/Design-Doc%3A-Configuration

**Comment by codeconsole** [comment]
Done https://github.com/sitemesh/sitemesh3/tree/master/spring-boot-starter-sitemesh
