### ISSUE TITLE
This can support domain matching layout?

### ISSUE THREAD

**Issue by wenzis** [sitemesh/sitemesh3#71]
org.sitemesh.webapp.WebAppContext.getRequestPath()返回的路径只包含了项目信息，去除了域名http://localhost:8080/,比如我对于http://l192.168.1.100:8080和http://l192.168.1.111:8080要使用不同的布局，这个就没办法了吗?

**Comment by codeconsole** [comment]
if you still need this feature, we are willing to implement it.   Let us know.

**Comment by codeconsole** [comment]
I can offer 2 solutions in the meantime:

Extend the [PathBasedDecoratorSelector](https://github.com/sitemesh/sitemesh3/blob/b135363532c6bc7ac105428acd2629828894014b/sitemesh/src/main/java/org/sitemesh/config/PathBasedDecoratorSelector.java#L42-L45)
```
    public String[] selectDecoratorPaths(Content content, C siteMeshContext) throws IOException {
        String[] result = pathMapper.get(siteMeshContext.getPath());
        return convertPaths(result == null ? EMPTY : result);
    }
```

You can get the `HttpServletRequest` object by calling `siteMeshContext.getRequest()`

Altneratively, you could all the work inside the page by dynamically setting the decorator using a meta tag:
e.g.

Here is an [example](https://github.com/sitemesh/sitemesh3/blob/3.2.0-M2/sitemesh-examples-hellowebapp/src/main/webapp/demo.jsp):

```html
    <c:if test="${not empty param.bootstrap}">
      <meta name="decorator" content="bootstrap.jsp${not empty param.doubled?',chaining.html':''}" />
    </c:if>
```
