### ISSUE TITLE
A release for fix #66

### ISSUE THREAD

**Issue by kdabir** [sitemesh/sitemesh3#74]
Could you please release 3.0.1 with fix for issue #66. It's been long time since the issue is fixed on master but I can not use it from maven central.

**Comment by codeconsole** [comment]
It is currently going through internal testing.  

In the meantime, feel free to add the following staging repository to your build:
https://oss.sonatype.org/content/groups/staging/

It might be several weeks before I push it to maven central.  I usually prefer to have significant testing on a high volume website before I push to maven central.
