### ISSUE TITLE
Help Page showing the difference between SiteMesh2 and SiteMesh3?

### ISSUE THREAD

**Issue by hansgru** [sitemesh/sitemesh3#77]
Please add a help page showing the difference between SiteMesh2 and SiteMesh3 and how
would one do a migration for existing applications with SiteMesh3 (since it doesn't seem to be a drop in replacement for SiteMesh2)

**Comment by codeconsole** [comment]
Sitemesh 3 is pretty simple to set up.  Have you looked at the documentation?

http://wiki.sitemesh.org/wiki/display/sitemesh3/Configuring+SiteMesh+3

**Comment by codeconsole** [comment]
https://github.com/sitemesh/sitemesh3/blob/master/README.md
