### ISSUE TITLE
The pjax parameters of filter 

### ISSUE THREAD

**Issue by zhang20084** [sitemesh/sitemesh3#78]
< mapping path="/ \* pjax \* " exclude="true" >

Why can't filter http://localhost/info?pjax=1

pjax parameters don't quote decorator 

！！！sos

**Comment by zhang20084** [comment]
pjax怎么处理。如何过滤pjax的页面不使用装饰器。

**Comment by codeconsole** [comment]
https://github.com/sitemesh/sitemesh3/issues/90
