### ISSUE TITLE
spelling error for exclude (exclue) configuration attribute

### ISSUE THREAD

**Issue by tveimo** [sitemesh/sitemesh3#79]
The attribute used for excluding paths seems to be exclue and not exclude. Am unsure if this is by design or an oversight?

**Comment by codeconsole** [comment]
where do you see this?

**Comment by casoc** [comment]
I just want to ask same question, and I see 'exclue' in document , this is URL:
http://wiki.sitemesh.org/wiki/display/sitemesh3/Configuring+SiteMesh+3
