### ISSUE TITLE
header of Last-Modified is got rid of by sitemesh3

### ISSUE THREAD

**Issue by ouonet** [sitemesh/sitemesh3#80]
Version: SiteMesh 3.0

I write a servlet for returning a image to browser. In response header, this servlet adds the header of Last-Modified .
If without SiteMesh , it works well.
If using SiteMesh , the response header don't have Last-Modified .
I am wondering
Firstly, Since SiteMesh will only intercept responses that set the Content-Type HTTP header to text/html, why it still processes the response header of other Content-Type?
Secondly, since it process header of Last-Modified ,why it will delete this header?

**Comment by codeconsole** [comment]
Do you have an example?

**Comment by codeconsole** [comment]
We were unable to replicate this behavior.   We verified by removing the asset exclusion rule from both hello world and spring boot example apps and confirmed that Last-Modified header correctly persisted for 
[http://localhost:8080/assets/logo.png](http://localhost:8080/assets/logo.png)
