### ISSUE TITLE
ajax problem

### ISSUE THREAD

**Issue by liyikai** [sitemesh/sitemesh3#83]
$.ajax({
				url : "${path }/management/ticket/expert/admin/indexdata",
				type : "get",
				data : {"status":status,"pageSize":pageSize,"pageNum":pageNum},
				dataType : "html",
				success : function(html){
					$('#dataView').html(html);
				},
				error : function(arg1, arg2, arg3){

				}
});
this is my ajax request.

public void doFilter(ServletRequest servletRequest, ServletResponse servletResponse, FilterChain filterChain) throws IOException, ServletException {
        if (!initialized) {
            throw new ServletException(getClass().getName() + ".init(FilterConfig) was not called");
        }
        String requestType =(String) ((HttpServletRequest)servletRequest).getHeader("X-Requested-With");   
        if(StringUtils.isBlank(requestType)&&!StringUtils.equals(AJAX_REQUEST_HEADER, requestType)){//is not ajax request
        	reloadIfNecessary();
        }
        filter.doFilter(servletRequest, servletResponse, filterChain);
    }
and this my Override method 
if the request is ajax, and then not excute reloadifNecessary method. but at last it also decorate my requset.
i want it not decorate my request, how can i do?

**Comment by codeconsole** [comment]
exclude the url
