### ISSUE TITLE
urlrewrite nonsupport 

### ISSUE THREAD

**Issue by zhang20084** [sitemesh/sitemesh3#84]
<rule>
        <from>^/([A-Za-z0-9]+)?$</from>
        <to type="forward">/api/index.jsp?code=$1</to>
</rule>

1、www.easyapi.com/test
2、www.easyapi.com/api/?code=test

the version 2.x is equal to the decorator

but version 3.0.1 is not equal to the decorator

**Comment by codeconsole** [comment]
https://github.com/sitemesh/sitemesh3/issues/90
