### ISSUE TITLE
Allow to have separate tag rules for the page being decorated and the decorating template

### ISSUE THREAD

**Issue by aantono** [sitemesh/sitemesh3#85]
Currently the same `contentProcessor` instance is being used to build the content for the page to be decorated and the decorating template which was applied.  The problem comes from having TagRules that modify the tags (like adding extra attributes, renaming tags, etc) or removing tags all-together.

One example is a rule to remove the `<script>` tags from the page-to-be-decorated, but we don't want to remove the `<script>` tags from the decorating template.

Would it be possible to add support for being able to have 2 separate TagRule registrations, or separate processors altogether to be able to install separate TagRuleBundles to appropriate ones only?

**Comment by codeconsole** [comment]
Feel free to create a pull request

**Comment by codeconsole** [comment]
You can simply create your own rule that checks whether it is processing the decorator or the content.
