### ISSUE TITLE
Don't pre-process content that has no decorators applied to it.

### ISSUE THREAD

**Issue by aantono** [sitemesh/sitemesh3#86]
It seems strange, and performance inefficient, that the urls that have no decorators to be applied to them are still being processed by `ContentProcessor` and all the TagRules get applied, regardless.

Should the default behavior be to only process the content if it is configured to have decorators that can be applied to it?

**Comment by tommyxu** [comment]
There is a small bug in SiteMeshFilter which considers pattern matches when exclusionPattern exists only.

For a easy workaround, write at exclusion rule in your config file. 

So I think the logic could be:
1. if no pattern match, skip wrap
2. if at least one pattern matches, check if exclusion pattern more specific.

@@ -99,22 +99,25 @@ public class SiteMeshFilter extends ContentBufferingFilter {
             ServletException {
         HttpServletRequest request = (HttpServletRequest) servletRequest;
         HttpServletResponse response = (HttpServletResponse) servletResponse;
+
+        String decoratorPattern = null;
+        if (decoratorSelector instanceof PathBasedDecoratorSelector) {
+            PathBasedDecoratorSelector<WebAppContext> pbds = (PathBasedDecoratorSelector<WebAppContext>) decoratorSelector;
+            decoratorPattern = pbds.getPathMapper().getPatternInUse(WebAppContext.getRequestPath(request));
+            if(decoratorPattern == null) {
+                // there is no decorator rule for this exclusion pattern
+                filterChain.doFilter(request, response);
+                return;
+            }
+        }
+        
         String exclusionPattern = getSelector().excludePatternInUse(request);
         if (exclusionPattern != null) {
             // Ability to override exclusion by more specific pattern
-            if (decoratorSelector instanceof PathBasedDecoratorSelector) {
-                PathBasedDecoratorSelector<WebAppContext> pbds = (PathBasedDecoratorSelector<WebAppContext>) decoratorSelector;
-                String decoratorPattern = pbds.getPathMapper().getPatternInUse(WebAppContext.getRequestPath(request));
-                if(decoratorPattern == null) {
-                    // there is no decorator rule for this exclusion pattern
-                    filterChain.doFilter(request, response);
-                    return;
-                }
-                if(PathMapper.isMoreSpecific(exclusionPattern, decoratorPattern)){
-                    // if the exclusion type is more specific
-                    filterChain.doFilter(request, response);
-                    return;
-                }
+            if(PathMapper.isMoreSpecific(exclusionPattern, decoratorPattern)){
+                // if the exclusion type is more specific
+                filterChain.doFilter(request, response);
+                return;
             }
         }
         super.doFilter(servletRequest, servletResponse, filterChain);

**Comment by codeconsole** [comment]
@musketyr

**Comment by musketyr** [comment]
@codeconsole could be. as long as it don't break following test the solution should be ok

https://github.com/sitemesh/sitemesh3/blob/master/sitemesh/src/test/java/org/sitemesh/webapp/SiteMeshFilterTest.java#L115

@tommyxu would you mind to send it as a pull request?

**Comment by codeconsole** [comment]
This is not a bug.  This is works as intended.

The reason is because all pages can be decorated or decorators can be overwritten by using a `meta` tag.

For instance:
```html
<meta name="decorator" content="bootstrap.jsp,chaining.html" />
```

Since site mesh will decorate any page with a more specific exclusion pattern, you can override this behavior by just creating an exclusion pattern for everything. 

For instance, simply adding the following to `sitemesh3.xml`
```html
<sitemesh>
  <mapping path="/*" exclude="true"/>
<sitemesh>
```

**Comment by codeconsole** [comment]
Re-opening this for a couple reasons:

1. If MetaTagSelector is not used, there is no need to process the content.
2. I am not sure of the need for the ability for a decorator to override and exclusion
