### ISSUE TITLE
Calling .resetBuffer() / .reset() has no effect on org.sitemesh.webapp.contentfilter.HttpServletResponseBuffer

### ISSUE THREAD

**Issue by sammyhk** [sitemesh/sitemesh3#87]
As titled, _org.sitemesh.webapp.contentfilter.HttpServletResponseBuffer_ should be reset-able. Now it does not implementing the .resetBuffer() and .reset(), causing the header/ content cannot be reset.

**Comment by codeconsole** [comment]
What is the use case this is addressing?   e.g.  Why do you want to reset the HttpServletResponseBuffer?

**Comment by sammyhk** [comment]
According to the javadoc of HttpServletResponse, reset()/ resetBuffer() should "Clears any data that exists in the buffer .... If the response has been committed, this method throws an IllegalStateException". But now calling reset()/ resetBuffer(), the HttpServletResponseBuffer do reset the underlay response but not resetting the content host by itself. From my point of view, this is really a bug as resulting no exception throw, but the outcome unexpected.

Given that ContentBufferingFilter uses HttpServletResponseBuffer, and the ContentBufferingFilter is an abstract implementation not directly bound by SiteMesh (by the javadoc itself). I think it is worth to fix this bug.

**Comment by tommyxu** [comment]
@sammyhk I don't know the spec. Could you please tell me under which scenario should we call reset/resetBuffer?

**Comment by codeconsole** [comment]
@sammyhk can you please answer @tommyxu 's question

**Comment by sammyhk** [comment]
Sorry for the late reply, actually the javadoc in the Servlet API is already the spec. If you really prefer to have a paper spec. document for the Servlet API, here it is: https://java.net/downloads/servlet-spec/Final/servlet-3_1-final.pdf

If you think it is TL;DR, let me recap the related parts here (Page 66):
"The `reset` method clears data in the buffer when the response is not committed. Headers, status codes and the state of calling `getWriter` or `getOutputStream` set by the servlet prior to the reset call *must* be cleared as well. The `resetBuffer` method clears content in the buffer if the response is not committed without clearing the headers and status code.
If the response is committed and the `reset` or `resetBuffer` method is called, an `IllegalStateException` *must* be thrown. The response and its associated buffer will be unchanged.
When using a buffer, the container must immediately flush the contents of a filled buffer to the client. If this is the first data that is sent to the client, the response is considered to be committed."

About this issue, because the data is buffered an no data is sent to the client, the response is NOT consider as committed, so `reset` and `resetBuffer` should be take effective. If you consider writing data to SiteMesh buffer is already "committed" the response (NOTE: `isCommitted` should return true), calling `reset` or `resetBuffer` should throw `IllegalStateException`.

**Comment by codeconsole** [comment]
I feel this unnecessarily complicates the code.  I really need a real world scenario / example app where these methods are needed to be called.   Please re-open this issue if you can provide such a scenario.
