### ISSUE TITLE
How decorating page with url parameters like Sitemesh2?

### ISSUE THREAD

**Issue by 0xbillw** [sitemesh/sitemesh3#89]
The Decorating with Parameters function is very useful in Dialog page pattern. suppose i have a page, it's path is /help.html. I want to show a dialog(div mock) use iframe tag, then I need not create another path like /dialog/help.html for dialog decorator, I just use a query parameter to do that in sitemesh2. It's very convenience!

**Comment by tommyxu** [comment]
Actually, what you want is a "exclude rule" on request parameter? right?

**Comment by tommyxu** [comment]
Do you mean we can decide a decoration template by a request parameter dynamically?

**Comment by dreamrepo** [comment]
Yes, [here](http://wiki.sitemesh.org/wiki/display/sitemesh/Decorating+with+Parameters) is sitemesh2's implement.

**Comment by zhang20084** [comment]
https://github.com/sitemesh/sitemesh3/issues/78

I also mention this issue.

**Comment by tommyxu** [comment]
Should we decide how to config this feature in the xml first ?

1. Specify a decoration template when request parameter A = ...
2. Stop decoration when request parameter A = ...

For point 1, maybe ?
...
  <mapping path="/index.*" decorator="/decorator.html"/> 
    <request-parameter name="A" value="a" decorator="/otherDecorator.html" />
  </mapping>
...

I don't know how to represent point 2. 

Maybe sitemesh-3 authors should design it first before we could implement it.

**Comment by zhang20084** [comment]
https://github.com/sitemesh/sitemesh3/issues/84
https://github.com/sitemesh/sitemesh3/issues/78

1、not supported pjax
2、the same page use UrlRewriteFilter ，2 versions are different.

**Comment by zhang20084** [comment]
disappointed

**Comment by codeconsole** [comment]
https://github.com/sitemesh/sitemesh3/issues/90
