### ISSUE TITLE
Decorating with Parameters?

### ISSUE THREAD

**Issue by zhang20084** [sitemesh/sitemesh3#90]
```
http://www.easyapi.com/info/free?pjax=1
```

Do not use decorator
What do I do

**Comment by codeconsole** [comment]
Parameters should not have any effect on page decorating.  Are you trying to create a rule based on parameters or the file part of the url?

**Comment by zhang20084** [comment]
But I can't, 
for example < mapping path="/ * pjax * " exclude="true" > It can't
please write a example, how to make the parameter using another decorator.
Thank you very much.

**Comment by zhang20084** [comment]
lose hope

**Comment by alexgaoyh** [comment]
`	<filter>  
		<filter-name>sitemesh3</filter-name>  
		<filter-class>com.alexgaoyh.MutiModule.Dubbo.RWSeperate.consumer.web.util.sitemesh.filter.ParamConfigurableSiteMeshFilter</filter-class>  
	</filter>  
	<filter-mapping>  
		<filter-name>sitemesh3</filter-name>  
		<url-pattern>/manager/*</url-pattern>  
	</filter-mapping>`

`package com.alexgaoyh.MutiModule.Dubbo.RWSeperate.consumer.web.util.sitemesh.filter;

import org.sitemesh.DecoratorSelector;
import org.sitemesh.builder.SiteMeshFilterBuilder;
import org.sitemesh.config.ConfigurableSiteMeshFilter;
import org.sitemesh.webapp.WebAppContext;

import com.alexgaoyh.MutiModule.Dubbo.RWSeperate.consumer.web.util.sitemesh.selector.ParamDecoratorSelector;

public class ParamConfigurableSiteMeshFilter extends ConfigurableSiteMeshFilter {

	protected void applyCustomConfiguration(SiteMeshFilterBuilder builder) {
        //获取原有默认配置装饰选择器
        DecoratorSelector<WebAppContext> defaultDecoratorSelector = builder.getDecoratorSelector();
        //赋给自定义装饰选择器，则自定义规则未匹配时调用默认选择器获取
        builder.setCustomDecoratorSelector(new ParamDecoratorSelector(defaultDecoratorSelector));
    }
}
`

`package com.alexgaoyh.MutiModule.Dubbo.RWSeperate.consumer.web.util.sitemesh.selector;

import java.io.IOException;

import javax.servlet.http.HttpServletRequest;

import org.sitemesh.DecoratorSelector;
import org.sitemesh.content.Content;
import org.sitemesh.webapp.WebAppContext;

import com.MutiModule.common.utils.StringUtilss;

public class ParamDecoratorSelector implements DecoratorSelector<WebAppContext> {

	private DecoratorSelector<WebAppContext> defaultDecoratorSelector;

	public ParamDecoratorSelector(DecoratorSelector<WebAppContext> defaultDecoratorSelector) {
		this.defaultDecoratorSelector = defaultDecoratorSelector;
	}

	@Override
	public String[] selectDecoratorPaths(Content content, WebAppContext context) throws IOException {
		HttpServletRequest request = context.getRequest();
		String decorator = request.getParameter("decorator");
		if (StringUtilss.isNotBlank(decorator) && decorator.equals("true")) {
			return new String[] {};
		}
		// Otherwise, fallback to the standard configuration
		return defaultDecoratorSelector.selectDecoratorPaths(content, context);
	}

}
`

**Comment by alexgaoyh** [comment]
`
	<filter>  
		<filter-name>sitemesh3</filter-name>  
		<filter-class>com.alexgaoyh.MutiModule.Dubbo.RWSeperate.consumer.web.util.sitemesh.filter.ParamConfigurableSiteMeshFilter</filter-class>  
	</filter>  
	<filter-mapping>  
		<filter-name>sitemesh3</filter-name>  
		<url-pattern>/manager/*</url-pattern>  
	</filter-mapping>
`

`
package com.alexgaoyh.MutiModule.Dubbo.RWSeperate.consumer.web.util.sitemesh.filter;

import org.sitemesh.DecoratorSelector;
import org.sitemesh.builder.SiteMeshFilterBuilder;
import org.sitemesh.config.ConfigurableSiteMeshFilter;
import org.sitemesh.webapp.WebAppContext;

import com.alexgaoyh.MutiModule.Dubbo.RWSeperate.consumer.web.util.sitemesh.selector.ParamDecoratorSelector;

public class ParamConfigurableSiteMeshFilter extends ConfigurableSiteMeshFilter {

	protected void applyCustomConfiguration(SiteMeshFilterBuilder builder) {
        //获取原有默认配置装饰选择器
        DecoratorSelector<WebAppContext> defaultDecoratorSelector = builder.getDecoratorSelector();
        //赋给自定义装饰选择器，则自定义规则未匹配时调用默认选择器获取
        builder.setCustomDecoratorSelector(new ParamDecoratorSelector(defaultDecoratorSelector));
    }
}
`

`
package com.alexgaoyh.MutiModule.Dubbo.RWSeperate.consumer.web.util.sitemesh.selector;

import java.io.IOException;

import javax.servlet.http.HttpServletRequest;

import org.sitemesh.DecoratorSelector;
import org.sitemesh.content.Content;
import org.sitemesh.webapp.WebAppContext;

import com.MutiModule.common.utils.StringUtilss;

public class ParamDecoratorSelector implements DecoratorSelector<WebAppContext> {

	private DecoratorSelector<WebAppContext> defaultDecoratorSelector;

	public ParamDecoratorSelector(DecoratorSelector<WebAppContext> defaultDecoratorSelector) {
		this.defaultDecoratorSelector = defaultDecoratorSelector;
	}

	@Override
	public String[] selectDecoratorPaths(Content content, WebAppContext context) throws IOException {
		HttpServletRequest request = context.getRequest();
		String decorator = request.getParameter("decorator");
		if (StringUtilss.isNotBlank(decorator) && decorator.equals("true")) {
			return new String[] {};
		}
		// Otherwise, fallback to the standard configuration
		return defaultDecoratorSelector.selectDecoratorPaths(content, context);
	}

}

`

**Comment by alexgaoyh** [comment]
[http://git.oschina.net/alexgaoyh/MutiModule-parent/commit/a1637c0bc02cc066430de103b9c0ef2fa1881904](url)

**Comment by alexgaoyh** [comment]
change web.xml file:  filter part to my filter 'com.alexgaoyh.MutiModule.Dubbo.RWSeperate.consumer.web.util.sitemesh.filter.ParamConfigurableSiteMeshFilter' 

`public class ParamConfigurableSiteMeshFilter extends ConfigurableSiteMeshFilter {

	protected void applyCustomConfiguration(SiteMeshFilterBuilder builder) {
        DecoratorSelector<WebAppContext> defaultDecoratorSelector = builder.getDecoratorSelector();
        builder.setCustomDecoratorSelector(new ParamDecoratorSelector(defaultDecoratorSelector));
    }
}`

`public class ParamDecoratorSelector implements DecoratorSelector<WebAppContext> {

	private DecoratorSelector<WebAppContext> defaultDecoratorSelector;

	public ParamDecoratorSelector(DecoratorSelector<WebAppContext> defaultDecoratorSelector) {
		this.defaultDecoratorSelector = defaultDecoratorSelector;
	}

	@Override
	public String[] selectDecoratorPaths(Content content, WebAppContext context) throws IOException {
		HttpServletRequest request = context.getRequest();
		String decorator = request.getParameter("decorator");
		if (StringUtilss.isNotBlank(decorator) && decorator.equals("true")) {
			return new String[] {};
		}
		// Otherwise, fallback to the standard configuration
		return defaultDecoratorSelector.selectDecoratorPaths(content, context);
	}

}`

**Comment by codeconsole** [comment]
The reason in this particular case is you are using the wrong mime type.  You should not be using text/html for ajax.

However, if this is still something you are interested in us addressing, we are happy to look into it.

**Comment by codeconsole** [comment]
This demonstrates that SiteMesh does not decorate json by default:

https://github.com/sitemesh/sitemesh3/commit/f68b087fd36928abe48bfc7595d946986c9e0917

If you want to decorate by parameters.  The simplest way is to add a meta tag inside the page you wish to decorate that is dynamic based on the parameter being present.

Here is an [example](https://github.com/sitemesh/sitemesh3/blob/3.2.0-M2/sitemesh-examples-hellowebapp/src/main/webapp/demo.jsp):

```
    <c:if test="${not empty param.bootstrap}">
      <meta name="decorator" content="bootstrap.jsp${not empty param.doubled?',chaining.html':''}" />
    </c:if>
```

If you can define a more specific need that can not be achieved with the current implementation, we are more than happy to offer a solution.
