### ISSUE TITLE
Switching from Sitemesh 3.0.0 to 3.0.1 causes everything to stop working

### ISSUE THREAD

**Issue by PawelJagus** [sitemesh/sitemesh3#91]
I have just recently tried to switch from version 3.0.0 to 3.0.1 and I am very disappointed with the result. What has been working flawlessly up till now, stopped to do so.

For example excluded views are ignored right now and for some views I am getting 403 forbidden response which I am not getting with version 3.0.0.

Have you changed something regarding security? Does the layout view need to be added to the security context now (by permitAll() method)? I am using Spring Security version 4.0.2.RELEASE together with Spring Social 2.0.2.RELEASE.

**Comment by codeconsole** [comment]
Spring Security shouldn't have an effect. Can you provide an example?

**Comment by codeconsole** [comment]
No example provided.
