### ISSUE TITLE
weblogic cannot decorate

### ISSUE THREAD

**Issue by kobe1700** [sitemesh/sitemesh3#97]
1. i use the sitemesh3 in my project，publish to tomcat it's OK， but publish the same war in weblogic，cannot decorate . why ???
2. after use sitemesh3, in my jsp ${pageContext.request.requestURI} is the jsp path ，not real request path ??? why?
   how to solve ???

**Comment by Nthalk** [comment]
Well, this looks like an issue with how weblogic decorates it's request. Even if you put your sitemesh filter NOT on FORWARD (the mechanism for retrieving the jsps), the servlet request path will be the JSP path.

I've made a fix for this here #117

**Comment by codeconsole** [comment]
If this is still occurring, I can get this resolved for you. 

It sounds like `FORWARD_SERVLET_PATH` is not being set prior to fowarding to the jsp.

Is this still an issue?
Are you at least using servlet API 3.1?

**Comment by codeconsole** [comment]
Sounds like this is no longer an issue.  If it is, please open a new ticket and we are more than happy to address it.
