### ISSUE TITLE
How to load the property within the body

### ISSUE THREAD

**Issue by jlynet** [sitemesh/sitemesh3#99]
How to load the property within the body,
Like sitemesh2 same. Use <body <decorator: getProperty property = "body.class" writeEntireProperty = "true" /> <decorator: getProperty property = "body.id" writeEntireProperty = "true" / >>

**Comment by codeconsole** [comment]
example?

**Comment by ai930** [comment]
yes

**Comment by ai930** [comment]
html of body element invalid。

**Comment by codeconsole** [comment]
decorator:
```html
<html>
<body>
   ...
   <sitemesh:write property='page.javascript'/>
</body>
</html>
```

webpage:
```html
<html>
<body>
  ...
  <content tag="javascript">
    <script type="text/javascript">
       alert('Hello World!')
    </script>
  </content>
</body>
</html>
```
